//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NongSanVietNam.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiN()
        {
            this.NongSans = new HashSet<NongSan>();
        }
    
        public int IDLoaiNS { get; set; }
        public string TenLoai { get; set; }
        public string HinhAnh { get; set; }
        public string MotaNgan { get; set; }
        public string NguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NongSan> NongSans { get; set; }
    }
}
